GA4 Implementation Bug Fix | Inbound Button not populating URL
govuk-one-login/ipv-cri-fraud-front pull request #433
Opened 2024-04-12 08:34 UTC by SophiaDWokoma

## Proposed changes
 
### What changed

- Navigation tracker data layer push was firing with URL, Link Domain and Link Path Parts all undefined. So I added data-link attribute which the tracker uses to populate the url parameter.

- Updated Package to latest version.

### Why did it change

Fix Bug 

### Issue tracking

- [DFC-454](https://govukverify.atlassian.net/browse/DFC-454)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

## Previously 
<img width="503" alt="Screenshot 2024-04-12 at 09 33 36" src="https://github.com/govuk-one-login/ipv-cri-fraud-front/assets/148252375/7968723c-fd29-49ff-bd99-07c2b642d2d8">

## Now 
<img width="659" alt="Screenshot 2024-04-12 at 09 31 37" src="https://github.com/govuk-one-login/ipv-cri-fraud-front/assets/148252375/2dba160f-0220-4505-877f-c30e7e034b50">

2024-04-12 08:51 UTC, di-fabs approved these changes

2024-04-12 08:59 UTC, Joanneyoung01 submitted a review, later dismissed

2024-04-19 07:48 UTC, di-fabs requested changes

2024-04-19 07:48 UTC, di-fabs commented on package.json
> +    "@govuk-one-login/one-login-analytics": "^1.0.2",
I think we need to use the latest version of analytics package:
https://www.npmjs.com/package/@govuk-one-login/frontend-analytics

cc @di-aholme @nickhealGDS

2024-04-26 11:04 UTC, gds-adhenderson approved these changes

2024-04-26 11:26 UTC, merged