[LIME-1192] Upgrade to aws-sdk V3
govuk-one-login/ipv-cri-fraud-front pull request #489
Opened 2024-09-17 12:43 UTC by SarahHillGDS

## Proposed changes

Upgrade aws-sdk V2 to V3 as AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024.

### What changed

Upgraded aws-sdk in package.json with V3. 
Dynamo session config and app.test were updated to reflect the V3 format

### Why did it change

Upgraded to V3 format

### Issue tracking

- [LIME-1192](https://govukverify.atlassian.net/browse/LIME-1192)

### Other considerations

There may be dependencies that use aws-sdk v2 as a transitive dependency. 

[LIME-1192]: https://govukverify.atlassian.net/browse/LIME-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-18 10:07 UTC, smsgds approved these changes

2024-09-18 10:08 UTC, smsgds requested changes

2024-09-18 10:08 UTC, smsgds commented on package.json
> +    "@aws-sdk/client-dynamodb": "^3.651.1",
Can we pin these to a version number (remove ^)

2024-09-19 09:14 UTC, ElliotMurphyGDS submitted a review, later dismissed

2024-09-20 14:34 UTC, smsgds approved these changes

2024-09-20 15:25 UTC, merged